export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const GET_USER_CART_REQUEST = "GET_USER_CART_REQUEST"
export const GET_USER_CART_SUCCESS = "GET_USER_CART_SUCCESS"
export const GET_USER_CART_FAILURE = "GET_USER_CART_FAILURE"

export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST"
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS"
export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE"

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST"
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS"
export const REMOVE_CART_ITEM_FAILURE = "REMOVE_CART_ITEM_FAILURE"

export const GET_USER_WISHLIST_REQUEST = "GET_USER_WISHLIST_REQUEST"
export const GET_USER_WISHLIST_SUCCESS = "GET_USER_WISHLIST_SUCCESS"
export const GET_USER_WISHLIST_FAILURE = "GET_USER_WISHLIST_FAILURE"

export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST"
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS"
export const ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE"

export const REMOVE_WISHLIST_ITEM_REQUEST = "REMOVE_WISHLIST_ITEM_REQUEST"
export const REMOVE_WISHLIST_ITEM_SUCCESS = "REMOVE_WISHLIST_ITEM_SUCCESS"
export const REMOVE_WISHLIST_ITEM_FAILURE = "REMOVE_WISHLIST_ITEM_FAILURE"
