// Create review
export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST"
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE"

// Get product reviews
export const GET_PRODUCT_REVIEWS_REQUEST = "GET_PRODUCT_REVIEWS_REQUEST"
export const GET_PRODUCT_REVIEWS_SUCCESS = "GET_PRODUCT_REVIEWS_SUCCESS"
export const GET_PRODUCT_REVIEWS_FAILURE = "GET_PRODUCT_REVIEWS_FAILURE"

// Get user reviews
export const GET_USER_REVIEWS_REQUEST = "GET_USER_REVIEWS_REQUEST"
export const GET_USER_REVIEWS_SUCCESS = "GET_USER_REVIEWS_SUCCESS"
export const GET_USER_REVIEWS_FAILURE = "GET_USER_REVIEWS_FAILURE"

// Update review
export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST"
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS"
export const UPDATE_REVIEW_FAILURE = "UPDATE_REVIEW_FAILURE"

// Delete review
export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const DELETE_REVIEW_FAILURE = "DELETE_REVIEW_FAILURE"

// Reset review state
export const RESET_REVIEW_STATE = "RESET_REVIEW_STATE"

