
export const FIND_PRODUCTS_SUCCESS="FIND_PRODUCTS_SUCCESS";
export const FIND_PRODUCTS_REQUEST="FIND_PRODUCTS_REQUEST";
export const FIND_PRODUCTS_FAILURE="FIND_PRODUCTS_FAILURE";

export const FIND_PRODUCT_BY_ID_SUCCESS="FIND_PRODUCT_BY_ID_SUCCESS";
export const FIND_PRODUCT_BY_ID_REQUEST="FIND_PRODUCT_BY_ID_REQUEST";
export const FIND_PRODUCT_BY_ID_FAILURE="FIND_PRODUCT_BY_ID_FAILURE";


// Action types for selling a product
export const SELL_PRODUCT_REQUEST = "SELL_PRODUCT_REQUEST";
export const SELL_PRODUCT_SUCCESS = "SELL_PRODUCT_SUCCESS";
export const SELL_PRODUCT_FAILURE = "SELL_PRODUCT_FAILURE";

// Action types for canceling a request
export const CANCEL_REQUEST_REQUEST = "CANCEL_REQUEST_REQUEST";
export const CANCEL_REQUEST_SUCCESS = "CANCEL_REQUEST_SUCCESS";
export const CANCEL_REQUEST_FAILURE = "CANCEL_REQUEST_FAILURE";


// Action types for getting sold products
export const GET_SOLD_PRODUCTS_REQUEST = "GET_SOLD_PRODUCTS_REQUEST";
export const GET_SOLD_PRODUCTS_SUCCESS = "GET_SOLD_PRODUCTS_SUCCESS";
export const GET_SOLD_PRODUCTS_FAILURE = "GET_SOLD_PRODUCTS_FAILURE";