export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCTS_SUCCESS"
export const FIND_PRODUCTS_REQUEST = "FIND_PRODUCTS_REQUEST"
export const FIND_PRODUCTS_FAILURE = "FIND_PRODUCTS_FAILURE"

export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS"
export const FIND_PRODUCT_BY_ID_REQUEST = "FIND_PRODUCT_BY_ID_REQUEST"
export const FIND_PRODUCT_BY_ID_FAILURE = "FIND_PRODUCT_BY_ID_FAILURE"

// Action types for selling a product
export const SELL_PRODUCT_REQUEST = "SELL_PRODUCT_REQUEST"
export const SELL_PRODUCT_SUCCESS = "SELL_PRODUCT_SUCCESS"
export const SELL_PRODUCT_FAILURE = "SELL_PRODUCT_FAILURE"

// Action types for canceling a request
export const CANCEL_REQUEST_REQUEST = "CANCEL_REQUEST_REQUEST"
export const CANCEL_REQUEST_SUCCESS = "CANCEL_REQUEST_SUCCESS"
export const CANCEL_REQUEST_FAILURE = "CANCEL_REQUEST_FAILURE"

// Action types for getting sold products
export const GET_SOLD_PRODUCTS_REQUEST = "GET_SOLD_PRODUCTS_REQUEST"
export const GET_SOLD_PRODUCTS_SUCCESS = "GET_SOLD_PRODUCTS_SUCCESS"
export const GET_SOLD_PRODUCTS_FAILURE = "GET_SOLD_PRODUCTS_FAILURE"

export const ACCEPT_SELL_REQUEST_REQUEST = "ACCEPT_SELL_REQUEST_REQUEST"
export const ACCEPT_SELL_REQUEST_SUCCESS = "ACCEPT_SELL_REQUEST_SUCCESS"
export const ACCEPT_SELL_REQUEST_FAILURE = "ACCEPT_SELL_REQUEST_FAILURE"

export const REJECT_SELL_REQUEST_REQUEST = "REJECT_SELL_REQUEST_REQUEST"
export const REJECT_SELL_REQUEST_SUCCESS = "REJECT_SELL_REQUEST_SUCCESS"
export const REJECT_SELL_REQUEST_FAILURE = "REJECT_SELL_REQUEST_FAILURE"

export const GET_SELL_REQUESTS_REQUEST = "GET_SELL_REQUESTS_REQUEST"
export const GET_SELL_REQUESTS_SUCCESS = "GET_SELL_REQUESTS_SUCCESS"
export const GET_SELL_REQUESTS_FAILURE = "GET_SELL_REQUESTS_FAILURE"

// Action types for accepting cancel request
export const ACCEPT_CANCEL_REQUEST_REQUEST = "ACCEPT_CANCEL_REQUEST_REQUEST"
export const ACCEPT_CANCEL_REQUEST_SUCCESS = "ACCEPT_CANCEL_REQUEST_SUCCESS"
export const ACCEPT_CANCEL_REQUEST_FAILURE = "ACCEPT_CANCEL_REQUEST_FAILURE"

// Action types for rejecting cancel request
export const REJECT_CANCEL_REQUEST_REQUEST = "REJECT_CANCEL_REQUEST_REQUEST"
export const REJECT_CANCEL_REQUEST_SUCCESS = "REJECT_CANCEL_REQUEST_SUCCESS"
export const REJECT_CANCEL_REQUEST_FAILURE = "REJECT_CANCEL_REQUEST_FAILURE"
